{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggstar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggstar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstar/ggstar_{{ version }}.tar.gz
  sha256: eda19b1be4f5719fdb251666b90f4d664b90b882c452d4b015a60727c3b55354

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-scales
  run:
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-scales

test:
  commands:
    - $R -e "library('ggstar')"           # [not win]
    - "\"%R%\" -e \"library('ggstar')\""  # [win]

about:
  home: https://github.com/xiangpin/ggstar/
  license: Artistic-2.0
  summary: To create the regular polygon layer for easily discernible shapes, we developed the package, it can be easily used if you know the 'ggplot2'.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggstar
# Title: Star Layer for 'ggplot2'
# Version: 1.0.1
# Authors@R: person(given = "Shuangbin", family = "Xu", role = c("aut", "cre"), email = "xshuangbin@163.com", comment = c(ORCID="0000-0003-3513-5362"))
# Description: To create the regular polygon layer for easily discernible shapes, we developed the package, it can be easily used if you know the 'ggplot2'.
# Depends: R (>= 3.5)
# Imports: grid, utils, ggplot2, scales, gridExtra
# Suggests: knitr, markdown, rmarkdown, prettydoc
# License: Artistic-2.0
# Encoding: UTF-8
# URL: https://github.com/xiangpin/ggstar/
# BugReports: https://github.com/xiangpin/ggstar/issues
# VignetteBuilder: knitr
# LazyData: false
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-02-10 08:47:51 UTC; xushuangbin
# Author: Shuangbin Xu [aut, cre] (<https://orcid.org/0000-0003-3513-5362>)
# Maintainer: Shuangbin Xu <xshuangbin@163.com>
# Repository: CRAN
# Date/Publication: 2021-02-10 10:40:29 UTC
